package com.minimarket.web.entity;

import javax.persistence.Entity;
import javax.persistence.Table;

// Generated 01-nov-2018 0:13:25 by Hibernate Tools 5.3.1.Final

/**
 * Marca generated by hbm2java
 */

@Table(name="Marca")
public class Marca implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String descripcion;

	public Marca() {
	}

	public Marca(String nombre, String descripcion) {
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
