package com.minimarket.web.entity;

import javax.persistence.Entity;
import javax.persistence.Table;

// Generated 01-nov-2018 0:13:25 by Hibernate Tools 5.3.1.Final

/**
 * Producto generated by hbm2java
 */

@Table(name="Producto")
public class Producto implements java.io.Serializable {

	private int sku;
	private String nombre;
	private int precio;
	private int stock;
	private int categoria;
	private int marca;
	private String descripcion;

	public Producto() {
	}

	public Producto(int sku, String nombre, int precio, int stock, int categoria, int marca, String descripcion) {
		this.sku = sku;
		this.nombre = nombre;
		this.precio = precio;
		this.stock = stock;
		this.categoria = categoria;
		this.marca = marca;
		this.descripcion = descripcion;
	}

	public int getSku() {
		return this.sku;
	}

	public void setSku(int sku) {
		this.sku = sku;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getPrecio() {
		return this.precio;
	}

	public void setPrecio(int precio) {
		this.precio = precio;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	public int getCategoria() {
		return this.categoria;
	}

	public void setCategoria(int categoria) {
		this.categoria = categoria;
	}

	public int getMarca() {
		return this.marca;
	}

	public void setMarca(int marca) {
		this.marca = marca;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
