package com.minimarket.web.entity;

import javax.persistence.Entity;
import javax.persistence.Table;

// Generated 01-nov-2018 0:13:25 by Hibernate Tools 5.3.1.Final

/**
 * Usuario generated by hbm2java
 */

@Table(name="Usuario")
public class Usuario implements java.io.Serializable {

	private Integer id;
	private String nombreUsuario;
	private String password;

	public Usuario() {
	}

	public Usuario(String nombreUsuario, String password) {
		this.nombreUsuario = nombreUsuario;
		this.password = password;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
